baseurl: /
languageCode: en-us
theme: hugo-theme-hello-friend
paginate: 5
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  contentTypeName: post
  defaultTheme: light
  showMenuItems: 2
  showReadingTime: yes
  custom_css: "style.css"
languages:
  en:
    copyright: ''
    dateFormatList: '2006-01-02'
    dateFormatSingle: '2006-01-02'
    keywords: ''
    menu:
      main:
        - identifier: archive
          name: Archives
          url: /archive
        - identifier: contact
          name: Contact Us
          url: /contact
        - identifier: okpi
          name: Oklahoma Policy Institute
          url: https://okpolicy.org
    menuMore: More
    minuteReadingTime: min read
    newerPosts: Newer posts
    olderPosts: Older posts
    params:
      logo:
        # logoHomeLink: "https://openjustice.okpolicy.org/" 
        logoText: Open Justice Oklahoma
        path: "/img/ojo-logo-yellow-cropped.png"
        alt: "Open Justice Oklahoma"
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: Unlocking the black box of our criminal justice system
    title: Open Justice Oklahoma Data Blog
    writtenBy: Written by
