baseurl: /
languageCode: en-us
theme: hugo-theme-hello-friend
paginate: 5
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  contentTypeName: post
  defaultTheme: light
  showMenuItems: 2
  showReadingTime: yes
  custom_css: "style.css"
languages:
  en:
    subtitle: data blog
    title: OJO
    copyright: ''
    dateFormatList: '2006-01-02'
    dateFormatSingle: '2006-01-02'
    keywords: ''
    menu:
      main:
        - identifier: archive
          name: Data Blog
          url: /archive
        - identifier: about
          name: About OJO
          url: /about
        - identifier: contact
          name: Staff
          url: /contact
        - identifier: okpi
          name: Oklahoma Policy Institute
          url: https://okpolicy.org
        - identifier: dashboards
          name: Live Data Dashboards
          url: /dashboard
    menuMore: More
    minuteReadingTime: min read
    newerPosts: Newer posts
    olderPosts: Older posts
    params:
      logo:
        # logoHomeLink: "https://openjustice.okpolicy.org/" 
        logoText: Open Justice Oklahoma
        path: "/img/ojo-logo-white-cropped.png"
        alt: "Open Justice Oklahoma"
    readMore: Read more
    readOtherPosts: Read other posts
    writtenBy: Written by
