baseurl: /
languageCode: en-us
theme: hugo-theme-hello-friend
paginate: 5
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  contentTypeName: post
  defaultTheme: dark
  showMenuItems: 2
  showReadingTime: yes
languages:
  en:
    copyright: ''
    dateFormatList: '2006-01-02'
    dateFormatSingle: '2006-01-02'
    keywords: ''
    menu:
      main:
        - identifier: about
          name: About Us
          url: /about
        - identifier: contact
          name: Contact Us
          url: /contact
    menuMore: Show more
    minuteReadingTime: min read
    newerPosts: Newer posts
    olderPosts: Older posts
    params:
      logo:
        # logoHomeLink: "https://openjustice.okpolicy.org/"
        # logoText: Open Justice Oklahoma
        path: "/img/ojo-logo-inverted-transparent.png"
        alt: "Open Justice Oklahoma"
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: Unlocking the black box of Oklahoma's criminal justice system
    title: Open Justice Oklahoma
    writtenBy: Written by
